### PR TITLE
Added CocoaPods support

### LINKED ISSUE #4: Should have Cocoapods integration

### PR DESCRIPTION
**Pull request by esttorhe**
# Fix #4

Hi there; sorry it took me so long from your [tweet](https://twitter.com/cparnot/status/579946923873988608) but I've been kind of busy lately :see_no_evil: 

Ok; long story short; I added support for [CocoaPods](http://cocoapods.org) here; its up and running with [Travis](https://travis-ci.org/esttorhe/ASCIImage) and the build is passing :sweat_smile: 
# Done
- Configure the Podspec
- Moved the sample project inside `Example` folder
- Modified the `README` to include installation details
- Added badges on top of the `README` that should change as soon as the podspec is sent
# TODO
- [ ] Push a tag on the repo to `1.0.0` since that's where the `Podspec` is pointing to
- [ ] Enable [Travis](https://travis-ci.org/esttorhe/ASCIImage) on your end to have the badges work accordingly
- [ ] Push the podspec to [`trunk`](https://guides.cocoapods.org/making/getting-setup-with-trunk.html) (If I did that I would have ended up being the owner of the pod instead of you; if you would like me to do that I would gladly do but you'll have to notify me of every new version you push in order to keep it up to date).

---

Hope this is all well :sparkles: 

MRW It finally flushes

### CODE REVIEW

**Comment by esttorhe** [comment]
PS. Let me know if you would like me to rebase all the commits into one single clean one and I'll gladly do it :bow:

**Comment by cparnot** [comment]
@esttorhe This is great, thanks! I am testing out the branch for the PR and running into some compiler errors, but I'll work it out to figure out what needs to be tweaked.

**Comment by esttorhe** [comment]
Well; in order for you to test you'll need to have CocoaPods installed on your machine

``` console
gem install cocoapods
```

And then inside the `Example` folder run

``` console
pod install
```

Then open up the `Workspace` and that should do the trick.

Let me know if you need any help :)

**Comment by cparnot** [comment]
Do you mean it won't compile or run the tests without cocoapods installed?

**Comment by esttorhe** [comment]
Yeah; sadly I realized that was going to be a problem when I was checking #4 

Now that I think about it I think it would be safe to leave the project as it was and only add the `pods` configuration; the problem is that I thought the projects were an `Example` but in reality they are just the test suites.

Perhaps I'll create a simple "example" project and will add it to the `Example` folder for the pod.

This is because users can run

``` console
pod try ASCIImage
```

And they get the `Example` project; I'll update this PR with that new approach if you like it.

**Comment by cparnot** [comment]
OK, indeed, I would really prefer that the project can be compiled for tests without cocoapod installed. I am totally fine with a cocoapods-specific example project. Thanks a lot for your patience, and sorry I have been slow to respond.

**Comment by esttorhe** [comment]
OK @cparnot; I fixed the project.

I "reverted" back to your project's structure (`Core`, `App-iOS`, `App-OSX` & `Tests`) at the root and the `Example` project for `CocoaPods` uses those same files but configured to use the `pod`.

That way there's no duplication of code and both versions compile and run the tests (one needing the `pod` the other as always).

Hopefully this will be good to go :trophy:

**Comment by esttorhe** [comment]
Also here's the [`TravisCI` build](https://travis-ci.org/esttorhe/ASCIImage/builds/58540878) with all tests in :green_heart:

**Comment by cparnot** [comment]
All good, thanks!

**Comment by cparnot** [comment]
@esttorhe Actually, what do you need me to do in the TODO list you had set up above?

**Comment by esttorhe** [comment]
@cparnot you'll need to push a tag `1.0.0` is the tag set on the `podspec` if you want to push a different version instead you'll have to update the [ASCIImage.podspec](https://github.com/cparnot/ASCIImage/blob/master/ASCIImage.podspec) version.

Then you'll have to install `CocoaPods` and push the podspec to [`trunk`](https://guides.cocoapods.org/making/getting-setup-with-trunk.html) (this to make the `pod` publicly available and to claim it as your own) and that would be it.

**Comment by cparnot** [comment]
@esttorhe Thanks again for all this! The tag has been added and the `pod trunk push` command executed.

**Comment by esttorhe** [comment]
It's alive! :+1: 

screen shot 2015-05-05 at 15 00 44

Thanks for bearing with me during the multiple iterations of this `PR` :bow:

**Comment by cparnot** [comment]
Thanks for being patient ;-)

**Pull request merged**
